"use client";

import Link from "next/link";
import { useActionState, useEffect, useId, useRef, useState } from "react";
import { closeMarketShiftAction } from "./actions";

type Summary = { shift: { id: string; outletName: string; openingCash: number }; cashSales: number; cashTransactions: number; digitalSales: number; digitalTransactions: number; expectedCash: number };
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export function CloseShiftForm({ summary }: { summary: Summary }) {
  const [state, action, pending] = useActionState(async (_: { error?: string; expectedCash?: number }, formData: FormData) => closeMarketShiftAction(formData), {}); const [closingCash, setClosingCash] = useState(""); const [note, setNote] = useState(""); const errorRef = useRef<HTMLParagraphElement>(null); const errorId = useId(); const amount = Number(closingCash); const variance = Number.isFinite(amount) ? amount - summary.expectedCash : 0; const noteRequired = Math.abs(variance) > 10_000;
  useEffect(() => { if (state.error) errorRef.current?.focus(); }, [state.error]);
  if (state.expectedCash !== undefined) return <section className="market-panel market-close-shift"><p className="market-eyebrow">Shift ditutup</p><h1>Rekonsiliasi tersimpan</h1><p>Kas yang seharusnya: {money(state.expectedCash)}.</p><Link className="market-checkout-button market-link-button" href="/kasir">Kembali ke kasir</Link></section>;
  return <section className="market-panel market-close-shift" aria-labelledby="close-title"><p className="market-eyebrow">Tutup shift · {summary.shift.outletName}</p><h1 id="close-title">Rekonsiliasi kas</h1><p>Hitung uang fisik di laci. Pembayaran digital tidak dimasukkan ke kas laci.</p><dl className="market-shift-summary"><div><dt>Modal awal</dt><dd>{money(summary.shift.openingCash)}</dd></div><div><dt>Penjualan tunai ({summary.cashTransactions})</dt><dd>{money(summary.cashSales)}</dd></div><div><dt>Kas seharusnya</dt><dd>{money(summary.expectedCash)}</dd></div><div><dt>Digital ({summary.digitalTransactions})</dt><dd>{money(summary.digitalSales)}</dd></div></dl><form action={action}><input name="shiftId" type="hidden" value={summary.shift.id} /><label htmlFor="closingCash">Uang kas yang dihitung</label><input id="closingCash" name="closingCash" inputMode="numeric" min="0" step="1" type="number" value={closingCash} onChange={(event) => setClosingCash(event.target.value)} aria-describedby={state.error ? errorId : undefined} aria-invalid={Boolean(state.error)} required />{closingCash ? <p className={noteRequired ? "market-variance is-warning" : "market-variance"}>Selisih {money(variance)} {noteRequired ? "— alasan wajib diisi." : "— masih dalam batas wajar."}</p> : null}{noteRequired ? <><label htmlFor="varianceNote">Alasan selisih</label><textarea id="varianceNote" name="varianceNote" value={note} onChange={(event) => setNote(event.target.value)} required rows={3} /></> : <input name="varianceNote" type="hidden" value="" />}{state.error ? <p id={errorId} ref={errorRef} className="market-form-error" role="alert" tabIndex={-1}>{state.error}</p> : null}<div className="market-dialog-actions"><Link href="/kasir">Kembali</Link><button className="market-danger-button" type="submit" disabled={pending || !closingCash || (noteRequired && !note.trim())}>{pending ? "Menutup…" : "Tutup shift"}</button></div></form></section>;
}
