"use client";

import Link from "next/link";
import { useEffect, useId, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { voidMarketSaleAction } from "./actions";

type Sale = { id: string; invoiceNumber: string; outletName: string; cashierName: string; total: number; paymentMethod: string; status: "COMPLETED" | "VOIDED"; voidReason: string | null; createdAt: Date };
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
const dateTime = (value: Date) => new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function SalesHistory({ sales, canVoid }: { sales: Sale[]; canVoid: boolean }) {
  const [target, setTarget] = useState<Sale | null>(null); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const dialogRef = useRef<HTMLDialogElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const errorRef = useRef<HTMLParagraphElement>(null); const errorId = useId(); const router = useRouter();
  useEffect(() => { if (target) dialogRef.current?.showModal(); else dialogRef.current?.close(); }, [target]);
  function close() { setTarget(null); setReason(""); setError(""); requestAnimationFrame(() => triggerRef.current?.focus()); }
  async function confirmVoid() { if (!target) return; setPending(true); setError(""); const result = await voidMarketSaleAction(target.id, reason); setPending(false); if (result.error) { setError(result.error); requestAnimationFrame(() => errorRef.current?.focus()); return; } close(); router.refresh(); }
  return <section className="market-stack" aria-labelledby="history-title"><div className="market-page-title"><div><p>Penjualan</p><h1 id="history-title">Riwayat transaksi</h1><span>100 transaksi terakhir pada outlet yang Anda akses.</span></div><div className="market-primary-actions"><Link href="/kasir">Transaksi baru</Link></div></div><section className="market-panel market-history"><h2 className="sr-only">Daftar transaksi</h2>{sales.length ? <div className="market-table-scroll"><table><caption className="sr-only">Riwayat transaksi Altora Market</caption><thead><tr><th scope="col">No. transaksi</th><th scope="col">Waktu & outlet</th><th scope="col">Pembayaran</th><th scope="col">Total</th><th scope="col"><span className="sr-only">Aksi</span></th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id}><td><strong>{sale.invoiceNumber}</strong><small>{sale.status === "VOIDED" ? `Dibatalkan: ${sale.voidReason}` : sale.cashierName}</small></td><td>{dateTime(sale.createdAt)}<small>{sale.outletName}</small></td><td>{sale.paymentMethod}</td><td><strong>{money(sale.total)}</strong></td><td className="market-row-actions"><Link href={`/kasir/struk/${sale.id}`}>Struk</Link>{canVoid && sale.status === "COMPLETED" ? <button ref={target?.id === sale.id ? triggerRef : undefined} type="button" onClick={(event) => { triggerRef.current = event.currentTarget; setTarget(sale); }}>Batalkan</button> : null}</td></tr>)}</tbody></table></div> : <div className="market-empty-state"><strong>Belum ada transaksi</strong><p>Transaksi dari Kasir akan tercatat di sini.</p></div>}</section><dialog ref={dialogRef} className="market-dialog" aria-labelledby="void-title" onClose={close}><form method="dialog"><div className="market-dialog-body"><h2 id="void-title">Batalkan transaksi?</h2><p>{target?.invoiceNumber}. Stok produk akan dikembalikan. Aksi ini tercatat di audit log.</p><label htmlFor="void-reason">Alasan pembatalan</label><textarea id="void-reason" value={reason} onChange={(event) => setReason(event.target.value)} aria-describedby={error ? errorId : undefined} aria-invalid={Boolean(error)} required rows={3} autoFocus />{error ? <p id={errorId} ref={errorRef} className="market-form-error" role="alert" tabIndex={-1}>{error}</p> : null}<div className="market-dialog-actions"><button type="button" onClick={close}>Kembali</button><button className="market-danger-button" type="button" disabled={pending || !reason.trim()} onClick={confirmVoid}>{pending ? "Membatalkan…" : "Batalkan transaksi"}</button></div></div></form></dialog></section>;
}
